<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Reply</code>
 */
class Reply extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>double res = 2;</code>
     */
    private $res = 0.0;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    /**
     * <code>double res = 2;</code>
     */
    public function getRes()
    {
        return $this->res;
    }

    /**
     * <code>double res = 2;</code>
     */
    public function setRes($var)
    {
        GPBUtil::checkDouble($var);
        $this->res = $var;
    }

}

