<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>double n1 = 2;</code>
     */
    private $n1 = 0.0;
    /**
     * <code>double n2 = 3;</code>
     */
    private $n2 = 0.0;
    /**
     * <code>.Request.Operacao op = 4;</code>
     */
    private $op = 0;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    /**
     * <code>double n1 = 2;</code>
     */
    public function getN1()
    {
        return $this->n1;
    }

    /**
     * <code>double n1 = 2;</code>
     */
    public function setN1($var)
    {
        GPBUtil::checkDouble($var);
        $this->n1 = $var;
    }

    /**
     * <code>double n2 = 3;</code>
     */
    public function getN2()
    {
        return $this->n2;
    }

    /**
     * <code>double n2 = 3;</code>
     */
    public function setN2($var)
    {
        GPBUtil::checkDouble($var);
        $this->n2 = $var;
    }

    /**
     * <code>.Request.Operacao op = 4;</code>
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * <code>.Request.Operacao op = 4;</code>
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \\Request_Operacao::class);
        $this->op = $var;
    }

}

