<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

/**
 * Protobuf enum <code>Request.Operacao</code>
 */
class Request_Operacao
{
    /**
     * <code>SOM = 0;</code>
     */
    const SOM = 0;
    /**
     * <code>SUB = 1;</code>
     */
    const SUB = 1;
    /**
     * <code>MUL = 2;</code>
     */
    const MUL = 2;
    /**
     * <code>DIV = 3;</code>
     */
    const DIV = 3;
}

